### ISSUE TITLE
Regarding your query at stackoverflow using bcrypt

### ISSUE THREAD

**Issue by dheeraj1997** [xakepp35/carsEvolution#1]
Couldn't find any other way to connect.
What exactly is the problem you facing with bcrypt??

You only having problem in validating password
Have you saved the salt while saving the password?

**Comment by xakepp35** [comment]
Hello! That is not the "problem", I wanted to do "syntactic sugar" to connect bcrypt to mongoose.

Like you have some user registered, it is stored in database, its salt is not stored, just a bcrypted password is stored. With thinks like sha-256 you could go simple - when you want to check if username and a password match, you check names, and password HASHES, and hashes match. with bcrypt it is not so, and you must to call SPECIAL bcrypt checking method. I was asking - could you embed it somehow to mongo, so that when i do password comparison - it would call it inside?

Could we better continue discussion there? https://stackoverflow.com/questions/55305780/how-to-embed-bcrypt-into-mongose-api-call

btw, it has no answer to the day..
